"""
Exports a trained RandomForestClassifier as a plain-array TypeScript data
file (src/lib/ml-forest-data.ts) for exact, from-scratch tree-traversal
inference in the Next.js app -- no Python runtime needed in production.

Run this after retraining to regenerate ml-forest-data.ts.
"""
import json
import joblib
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

df = pd.read_csv("journeys_v3.csv")
FEATURES = [
    "hour", "distance_km", "route_deviation_m", "unexpected_stop_s",
    "nearby_safe_zone_count", "nearby_police_or_hospital",
    "community_reports_nearby", "is_weekend", "historical_crime_index",
]
X = df[FEATURES]
y = df["high_risk"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

clf = RandomForestClassifier(n_estimators=40, max_depth=5, class_weight="balanced", random_state=42, n_jobs=2)
clf.fit(X_train, y_train)
joblib.dump(clf, "high_risk_rf_classifier.pkl")

trees = []
for est in clf.estimators_:
    t = est.tree_
    trees.append({
        "feature": t.feature.tolist(),
        "threshold": t.threshold.tolist(),
        "children_left": t.children_left.tolist(),
        "children_right": t.children_right.tolist(),
        "value": (t.value[:, 0, 1] / t.value[:, 0, :].sum(axis=1)).tolist(),
    })

lines = [
    "// Exact export of the trained RandomForestClassifier (see",
    "// /ml/safety_score_training_v4.ipynb). Generated by",
    "// /ml/export_forest_to_ts.py -- do not hand-edit; regenerate by retraining",
    "// and rerunning that script.",
    f"export const RF_FEATURE_ORDER = {json.dumps(FEATURES)} as const;",
    "",
    "export interface RfTree {",
    "  feature: number[];",
    "  threshold: number[];",
    "  children_left: number[];",
    "  children_right: number[];",
    "  value: number[];",
    "}",
    "",
    f"export const RF_TREES: RfTree[] = {json.dumps(trees)};",
]
with open("ml-forest-data.ts", "w") as f:
    f.write("\n".join(lines) + "\n")

print("Exported ml-forest-data.ts")
